### ISSUE TITLE
Shutdown after 40 Sek

### ISSUE THREAD

**Issue by CleariCYT** [crashworks3d/Iron_Man_Servo#2]
Hey, I have wired everything exactly as described in the circuit diagram. However, I have the problem that the Arduino turns off after 40 seconds when the helmet is open. I can no longer wake it up using the button.  I always have to disconnect and reconnect the power supply and restart the Arduino. What could be the reason for this? I looked through the code and did not find anything that could cause this.

**Comment by i3creations** [comment]
If you are using a smart phone charger as your power source, the charger will shut off after a period of time because the arduino does not draw enough current for the charger to think it is charging something.  You will need a "keep alive" circuit to trick the battery.  We have a device named PENELOPE for that: https://www.ebay.com/itm/403483620977

**Comment by CleariCYT** [comment]
Ah ok yes that explains the problem. You can also solve the problem by flashing a LED every few seconds for about 20ms or not? So you would have to pull enough mA in the right interval so that the powerbank does not go out

**Comment by i3creations** [comment]
Possibly.  Just enough of a current draw to trick the battery.

**Comment by i3creations** [comment]
Issue due to smart phone charger circuit.  Resolution is to add a "keep alive" circuit.
